<meta charset="utf-8"/>
<?php
define('APP_DIR', dirname(__FILE__) . DIRECTORY_SEPARATOR);
define('CACHE_DIR', APP_DIR . '/cache');
define('CACHE_DURATION', 7200);
require_once 'autoloader.php';

//$rss_link = array(
//    'http://afamily.vn/trang-chu.rss',
//    'http://afamily.vn/dep.rss',
//    'http://afamily.vn/doi-song.rss',
//    'http://afamily.vn/cong-so.rss',
//    'http://afamily.vn/an-ngon.rss',
//    'http://afamily.vn/tinh-yeu-hon-nhan.rss',
//    'http://afamily.vn/suc-khoe.rss',
//    'http://afamily.vn/tam-su.rss',
//    'http://afamily.vn/me-va-be.rss',
//    'http://afamily.vn/nha-hay.rss',
//    'http://afamily.vn/hau-truong.rss',
//    'http://afamily.vn/giai-tri.rss',
//    'http://afamily.vn/chuyen-la.rss'
//);
$rss_link = array(
    'http://www.dantri.com.vn/trangchu.rss',
    'http://www.dantri.com.vn/xa-hoi.rss',
    'http://www.dantri.com.vn/chinh-tri.rss',
    'http://www.dantri.com.vn/doi-song.rss',
    'http://www.dantri.com.vn/phong-suky-su.rss',
    'http://www.dantri.com.vn/giao-thong.rss',
    'http://www.dantri.com.vn/moi-truong.rss',
    'http://www.dantri.com.vn/ho-so.rss',
    'http://www.dantri.com.vn/Thegioi.rss',
    'http://www.dantri.com.vn/dong-a.rss',
    'http://www.dantri.com.vn/eu--nga.rss',
    'http://www.dantri.com.vn/chau-my.rss',
    'http://www.dantri.com.vn/diem-nong.rss',
    'http://www.dantri.com.vn/tu-lieu.rss',
    'http://www.dantri.com.vn/kieu-bao.rss',
    'http://www.dantri.com.vn/tet-viet-xa-xu.rss',
    'http://www.dantri.com.vn/The-Thao.rss',
    'http://www.dantri.com.vn/the-thao-trong-nuoc.rss',
    'http://www.dantri.com.vn/the-thao-quoc-te.rss',
    'http://www.dantri.com.vn/bong-da-trong-nuoc.rss',
    'http://www.dantri.com.vn/bong-da-chau-au.rss',
    'http://www.dantri.com.vn/bong-da-anh.rss',
    'http://www.dantri.com.vn/bong-da-tbn.rss',
    'http://www.dantri.com.vn/tennis.rss',
    'http://www.dantri.com.vn/giaoduc-khuyenhoc.rss',
    'http://www.dantri.com.vn/tin-tuyen-sinh.rss',
    'http://www.dantri.com.vn/khuyen-hoc.rss',
    'http://www.dantri.com.vn/guong-sang.rss',
    'http://www.dantri.com.vn/apollo-vlog.rss',
    'http://www.dantri.com.vn/nghe-hot.rss',
    'http://www.dantri.com.vn/tamlongnhanai.rss',
    'http://www.dantri.com.vn/danh-sach-ung-ho.rss',
    'http://www.dantri.com.vn/danh-sach-ket-chuyen.rss',
    'http://www.dantri.com.vn/hoan-canh.rss',
    'http://www.dantri.com.vn/kinhdoanh.rss',
    'http://www.dantri.com.vn/tai-chinh-dau-tu.rss',
    'http://www.dantri.com.vn/thi-truong.rss',
    'http://www.dantri.com.vn/doanh-nghiep.rss',
    'http://www.dantri.com.vn/bao-ve-ntd.rss',
    'http://www.dantri.com.vn/quoc-te.rss',
    'http://www.dantri.com.vn/nha-dat.rss',
    'http://www.dantri.com.vn/van-hoa.rss',
    'http://www.dantri.com.vn/doi-song-van-hoa.rss',
    'http://www.dantri.com.vn/san-khau-dan-gian.rss',
    'http://www.dantri.com.vn/du-lich-kham-pha.rss',
    'http://www.dantri.com.vn/van-hoc.rss',
    'http://www.dantri.com.vn/dien-anh.rss',
    'http://www.dantri.com.vn/am-nhac.rss',
    'http://www.dantri.com.vn/giaitri.rss',
    'http://www.dantri.com.vn/sao-viet.rss',
    'http://www.dantri.com.vn/hollywood.rss',
    'http://www.dantri.com.vn/chau-a.rss',
    'http://www.dantri.com.vn/thoi-trang.rss',
    'http://www.dantri.com.vn/xem-an-choi.rss',
    'http://www.dantri.com.vn/skphapluat.rss',
    'http://www.dantri.com.vn/nhipsongtre.rss',
    'http://www.dantri.com.vn/nguoi-viet-tre.rss',
    'http://www.dantri.com.vn/phong-su-tre.rss',
    'http://www.dantri.com.vn/english-champion.rss',
    'http://www.dantri.com.vn/tinhyeu-gioitinh.rss',
    'http://www.dantri.com.vn/tinh-yeu.rss',
    'http://www.dantri.com.vn/gia-dinh.rss',
    'http://www.dantri.com.vn/goc-tam-hon.rss',
    'http://www.dantri.com.vn/suckhoe.rss',
    'http://www.dantri.com.vn/kien-thuc-gioi-tinh.rss',
    'http://www.dantri.com.vn/tu-van.rss',
    'http://www.dantri.com.vn/lam-dep.rss',
    'http://www.dantri.com.vn/suc-manh-tri-thuc.rss',
    'http://www.dantri.com.vn/suc-manh-so.rss',
    'http://www.dantri.com.vn/khoa-hoc.rss',
    'http://www.dantri.com.vn/thu-thuat.rss',
    'http://www.dantri.com.vn/tu-van-so.rss',
    'http://www.dantri.com.vn/nhan-tai-dat-viet.rss',
    'http://www.dantri.com.vn/nghe-nhin.rss',
    'http://www.dantri.com.vn/otoxemay.rss',
    'http://www.dantri.com.vn/thi-truong-xe.rss',
    'http://www.dantri.com.vn/van-hoa-xe.rss',
    'http://www.dantri.com.vn/tu-van-xe.rss',
    'http://www.dantri.com.vn/dua-xe.rss',
    'http://www.dantri.com.vn/gia-xe.rss',
    'http://www.dantri.com.vn/diendan-bandoc.rss',
    'http://www.dantri.com.vn/tu-van-phap-luat.rss',
    'http://www.dantri.com.vn/hoi-am.rss',
    'http://www.dantri.com.vn/goc-anh.rss',
    'http://www.dantri.com.vn/dien-dan.rss',
    'http://www.dantri.com.vn/giao-duc.rss',
    'http://www.dantri.com.vn/xa-hoi.rss',
    'http://www.dantri.com.vn/the-gioi.rss',
    'http://www.dantri.com.vn/chuyen-la.rss',
    'http://www.dantri.com.vn/blog.rss',
    'http://www.dantri.com.vn/viec-lam.rss',
    'http://www.dantri.com.vn/chinh-sach.rss',
    'http://www.dantri.com.vn/thi-truong-viec-lam.rss',
    'http://www.dantri.com.vn/chung-toi-noi.rss',
    'http://www.dantri.com.vn/dao-tao.rss',
    'http://www.dantri.com.vn/xkld.rss'
);
$feed = new SimplePie();
$feed->set_feed_url($rss_link);
$feed->enable_cache();
$feed->set_cache_duration(CACHE_DURATION);
$feed->set_cache_location(CACHE_DIR);
$feed->init();
$feed->handle_content_type();
foreach ($feed->get_items() as $item):
    echo $item->get_title() . ' - ' . $item->get_permalink();
    echo '<br />';
endforeach;